import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import L from'leaflet';import'leaflet/dist/leaflet.css';import'./style.css';

type Charger={id:string,name:string,city:string,lat:number,lng:number,power:number,connector:string,price:number|null,condition?:string,source:string,verified:string};
const chargers:Charger[]=[
{id:'demo-sev-1',name:'Punto DEMO supermercado',city:'Sevilla',lat:37.3891,lng:-5.9845,power:22,connector:'Tipo 2',price:0,source:'DEMO',verified:'Pendiente'},
{id:'demo-hue-1',name:'Punto DEMO centro comercial',city:'Huelva',lat:37.2614,lng:-6.9447,power:22,connector:'Tipo 2',price:0,condition:'Con compra',source:'DEMO',verified:'Pendiente'},
{id:'demo-mad-1',name:'Punto DEMO municipal',city:'Madrid',lat:40.4168,lng:-3.7038,power:50,connector:'CCS',price:0,source:'DEMO',verified:'Pendiente'}
];

function MapView({position,onlyFree}:{position:[number,number]|null,onlyFree:boolean}){
 const ref=useRef<HTMLDivElement>(null),mapRef=useRef<L.Map|null>(null);
 useEffect(()=>{if(!ref.current||mapRef.current)return;const m=L.map(ref.current).setView([40.2,-3.7],6);mapRef.current=m;
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(m);
 chargers.filter(c=>!onlyFree||c.price===0).forEach(c=>L.circleMarker([c.lat,c.lng],{radius:9,weight:3,fillOpacity:.9}).addTo(m).bindPopup('<b>'+c.name+'</b><br>'+c.city+' · '+c.power+' kW · '+c.connector+'<br><b>GRATIS · DEMO</b>'));
 setTimeout(()=>m.invalidateSize(),50);return()=>{m.remove();mapRef.current=null}},[onlyFree]);
 useEffect(()=>{const m=mapRef.current;if(!m||!position)return;L.circleMarker(position,{radius:8,weight:3,fillOpacity:1}).addTo(m).bindPopup('Tu ubicación').openPopup();m.setView(position,13)},[position]);
 return <div id="map" ref={ref}/>;
}

function App(){
 const[tab,setTab]=useState('mapa'),[pos,setPos]=useState<[number,number]|null>(null),[msg,setMsg]=useState('Sin localizar'),[onlyFree,setOnlyFree]=useState(true);
 const[origin,setOrigin]=useState('Mi ubicación'),[destination,setDestination]=useState(''),[soc,setSoc]=useState(90),[reserve,setReserve]=useState(15),[routeResult,setRouteResult]=useState(''),[routing,setRouting]=useState(false);
 const locate=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{const q:[number,number]=[p.coords.latitude,p.coords.longitude];setPos(q);setMsg(q[0].toFixed(4)+', '+q[1].toFixed(4))},()=>setMsg('Permiso de ubicación no concedido'),{enableHighAccuracy:true,timeout:12000}):setMsg('GPS no disponible');
 const nav=(c:Charger)=>window.open('https://www.google.com/maps/dir/?api=1&destination='+c.lat+','+c.lng,'_blank');
 const geocode=async(q:string)=>{const r=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(q));const j=await r.json();if(!j.length)throw new Error('No encuentro esa localidad');return [Number(j[0].lat),Number(j[0].lon)] as [number,number]};
 const calculateRoute=async()=>{try{setRouting(true);setRouteResult('Calculando ruta…');let a:[number,number];if(origin.trim().toLowerCase().startsWith('mi ubicación')){if(!pos)throw new Error('Pulsa primero “Mi ubicación” para usar tu GPS');a=pos}else a=await geocode(origin);const b=await geocode(destination);const r=await fetch('https://router.project-osrm.org/route/v1/driving/'+a[1]+','+a[0]+';'+b[1]+','+b[0]+'?overview=false');const j=await r.json();if(j.code!=='Ok'||!j.routes?.length)throw new Error('No se ha podido calcular la ruta por carretera');const km=j.routes[0].distance/1000,minutes=j.routes[0].duration/60;const battery=57.5,consumption=17,energy=km*consumption/100,start=battery*soc/100,min=battery*reserve/100,available=Math.max(0,start-min),need=Math.max(0,energy-available),arrival=soc-energy/battery*100;setRouteResult('DISTANCIA: '+km.toFixed(0)+' km · TIEMPO: '+Math.floor(minutes/60)+' h '+Math.round(minutes%60)+' min · ENERGÍA EST.: '+energy.toFixed(1)+' kWh · SOC llegada teórico: '+Math.max(0,arrival).toFixed(0)+'% · '+(need>0?'NECESITAS RECARGAR aprox. '+need.toFixed(1)+' kWh para mantener '+reserve+'% de reserva.':'Puedes llegar sin recargar manteniendo aproximadamente la reserva indicada.'))}catch(e){setRouteResult('⚠️ '+(e instanceof Error?e.message:'Error calculando la ruta'))}finally{setRouting(false)}};
 return <main><header><div><b>⚡ CargaGratis España</b><small>V2 · mapa + GPS</small></div><button onClick={locate}>◎ Mi ubicación</button></header>
 <nav>{['mapa','viaje','favoritos','vehículo'].map(x=><button key={x} className={tab===x?'on':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 {tab==='mapa'&&<section><div className="titleRow"><div><h1>Cargadores</h1><p className="muted">España · estructura preparada para datos OCPI/Reve</p></div><label className="switch"><input type="checkbox" checked={onlyFree} onChange={e=>setOnlyFree(e.target.checked)}/> Solo gratis</label></div>
 <p className="notice">⚠️ Los 3 puntos actuales siguen siendo DEMO. No se mostrarán como reales hasta verificar fuente y tarifa.</p><div className="location">📍 {msg}</div><MapView position={pos} onlyFree={onlyFree}/>
 <div className="cards">{chargers.filter(c=>!onlyFree||c.price===0).map(c=><article key={c.id}><div className="badge">DEMO</div><h3>{c.name}</h3><p>{c.city} · {c.power} kW · {c.connector}</p><strong>{c.condition?'Gratis condicionado · '+c.condition:'Gratis'}</strong><small>Fuente: {c.source} · Verificación: {c.verified}</small><button onClick={()=>nav(c)}>Navegar</button></article>)}</div></section>}
 {tab==='viaje'&&<section><h1>Ruta 0 €</h1><p className="muted">Planificador energético V2.1 · cálculo por carretera</p><label>Origen<input value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="Mi ubicación o localidad"/></label><label>Destino<input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Ej. Barcelona"/></label><div className="grid"><label>SOC salida (%)<input type="number" value={soc} min="1" max="100" onChange={e=>setSoc(Number(e.target.value))}/></label><label>Reserva mínima (%)<input type="number" value={reserve} min="0" max="50" onChange={e=>setReserve(Number(e.target.value))}/></label></div><button className="primary" disabled={routing||!destination.trim()} onClick={calculateRoute}>{routing?'Calculando…':'Calcular ruta gratuita'}</button>{routeResult&&<div className="routeResult">{routeResult}</div>}<p className="notice">El cálculo usa por ahora el perfil Model Y SR: 57,5 kWh útiles y 17 kWh/100 km. La siguiente versión colocará automáticamente cargadores gratuitos verificados en el recorrido.</p></section>}
 {tab==='favoritos'&&<section><h1>Favoritos</h1><p>Aquí aparecerán tus cargadores guardados.</p></section>}
 {tab==='vehículo'&&<section><h1>Mi vehículo</h1><label>Modelo<input defaultValue="Tesla Model Y Standard Range"/></label><label>Batería útil (kWh)<input type="number" defaultValue="57.5"/></label><label>Consumo (kWh/100 km)<input type="number" defaultValue="17"/></label><button className="primary">Guardar perfil</button></section>}
 <footer>V2 · Datos de cargadores actuales: DEMO</footer></main>
}createRoot(document.getElementById('root')!).render(<App/>);